### ISSUE TITLE
NanoVNA Firmware version 1.1.00 - Incomplete menu image .

### ISSUE THREAD

**Issue by oridolfi** [hyang-gith/DiSlord#1]
I have just updated my device and found that the Display -> Scale -> Scale/Div and Reference Position menus are not being displayed properly. The right/upper corner of the image shows previous menus images and as result, some buttons for this settings are missing.

Hope this feedback helps to improve your astonishing software.

Best regards
Oscar

**Comment by oridolfi** [comment]
I reported this issue on https://github.com/DiSlord/NanoVNA-D/issues/27.

**Comment by DiSlord** [comment]
Not understand problem, but look like Scale/Ref button not draw? You use SD card? If yes remove it from device
